version: 2
updates:
  - package-ecosystem: bundler
    directory: /site
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct

  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: weekly
